config/routes.rb
Matcher::Application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }  

  resources :users do
    member do
      get :rater, :rated
    end
  end
  resources :picposts
  resources :picture_ratings
  resources :picture_comments
  resources :comment_ratings, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]

  root to: 'static_pages#home'

  match '/comment', to: 'picposts#view_comments'
  match '/user_picpost', to: 'users#show_picposts'
  match '/user_comment', to: 'users#show_comments'
  match '/user_feedback', to: 'users#show_feedback'
  match '/user_favorite', to: 'users#show_favorites'

  match '/signup', to: 'users#new'

  match '/welcome', to: 'static_pages#splash'
  match '/about', to: 'static_pages#about'
  match '/help', to: 'static_pages#help'
  match '/contact', to: 'static_pages#contact'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @picposts = Picpost.all
  end

  def help
  end

  def about
  end

  def contact
  end

  def splash
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_comment_form.html.erb
<div class="post_comment_container" >
<span style="font-size: x-small;">Add comment</span>
  <%= form_for(current_user.picture_comments.build(picpost_id: @picpost.id), remote: true) do |f| %>
    <%= f.hidden_field :picpost_id, :value => @picpost.id %>
    <%= f.text_area :comment, rows: 1, cols: 10 %>
    <%= f.submit "Post", class: "button-link" %>
  <% end %>
</div>

<div class="comments_list">
  <% @picpost.picture_comments.each do |picture_comment| %>
    <div class="usercomment round">
      <span class="full_comment"><span class="bold"><i class="icon-user"></i><%= picture_comment.user.name %></span> <span style="opacity: .7;">&nbsp;<%= picture_comment.comment %></span></span>
      <div class="rate_comment">
        <% if @picpost.user == current_user and picture_comment.user != current_user %>
          <% comment_rating_id = "comment_rating_#{picture_comment.id}" %>
          <div id="<%= comment_rating_id %>" class="rating_icon_box" style="display: none;">
            <%= render 'shared/rate_comment_form', picture_comment: picture_comment %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/static_pages/_comment_form_container.html.erb
<div id=<%= "comment_list_#{@picpost.id}" %> >
  <%= render 'static_pages/comment_form', picpost: @picpost %>
</div>

app/views/static_pages/_modal.html.erb
<div id="comment_modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="comment" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
    <h3 id="comment">Comments</h3>
  </div>
  <div class="modal-body">
    <p>One fine body...</p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary">Save changes</button>
  </div>
</div>

app/views/static_pages/_rating_form.html.erb
<% if !user_signed_in? %>
  <div style="padding-bottom: 8px;">
    <div style="float: left;">
      <span class="rating_icon_container"><i class="icon-thumbs-up"></i>Dashing ( <%= picpost.get_likes %> )</span>
    </div>
    <div style="float: left;">
      <span class="rating_icon_container"><i class="icon-thumbs-down"></i>Clashing ( <%= picpost.get_dislikes %> )</span>
    </div>

    <div>
      <span class="rating_icon_container" ><i class="icon-comment"></i></span>
    </div>

  </div>
<% else %>

  <div>

    <% rating = current_user.rating(picpost) %>
    <% (rating == nil) ? submit_form = "$(this).submit();" : submit_form = "" %>
    <% (rating == nil) ? html_class = "rating_icon_container" : html_class = "rating_icon_container_disabled" %>

    <div style="float: left;">
      <%= form_for(current_user.picture_ratings.build(picpost_id: picpost.id), remote: true) do |f| %>
      
        <%= f.hidden_field :rating, :value => true %>
        <%= f.hidden_field :picpost_id, :value => picpost.id %>
        <span class="<%= html_class %>" onclick="<%= submit_form %>"><i class="icon-thumbs-up"></i>Dashing ( <%= picpost.get_likes %> )</span>
      <% end %>

    </div>

    <div style="float: left;">
      <%= form_for(current_user.picture_ratings.build(picpost_id: picpost.id), remote: true) do |f| %>
  
        <%= f.hidden_field :rating, :value => false %>
        <%= f.hidden_field :picpost_id, :value => picpost.id %>
        <span class="<%= html_class %>" onclick="<%= submit_form %>"><i class="icon-thumbs-down"></i>Clashing ( <%= picpost.get_dislikes %> )</span>
      <% end %>
    </div>

    <div style="float: left;">
      <%= form_tag(comment_path(picpost_id: picpost.id), remote: true) do |f| %>
        <%= hidden_field_tag :picpost_id, picpost.id %>
        <% comment_id = "comment_#{picpost.id}" %>
        <span class="rating_icon_container comment_form_button" onclick="register_click($(this));"id="<%= comment_id %>"><i class="icon-comment"></i></span>

      <% end %>

    </div>
    <div class="clearfix"></div>
  </div>

  <% if rating != nil %>
    <% (rating == true) ? icon = "icon-thumbs-up" : icon = "icon-thumbs-down" %>
    <%= form_for(current_user.picture_ratings.find_by_picpost_id(picpost.id), html: { method: :delete }, remote: true) do |f| %>
      <div class="undo"><span class="undo_icon_container" onclick="$(this).submit();">Undo <i class="<%= icon %>"></i></span></div>
    <% end %> 
  <% end %>

<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

<!-- Button to trigger modal -->
<button id="trigger">OPEN</button>
 
<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Modal header</h3>
  </div>
  <div class="modal-body">
    <p>One fine body…</p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary">Save changes</button>
  </div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="row">
  <div class="span12">
    <div class="span4 offset4">
      <div style="margin-left: 50px;"><%#= image_tag('runway.png', alt: "The Runway") %></div>
    </div>
  </div>
</div>

<%= render 'modal' %>

<div class="row">
  <div class="span12">
    <%= render 'shared/picposts', picposts: @picposts %>
  </div>
</div>

app/views/static_pages/splash.html.erb
<div style="margin-left: auto; margin-right: auto; width: 800px; padding-left: 100px;">
  <%= image_tag("splash_page1.png") %>
</div>