config/routes.rb
Matcher::Application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }  

  resources :users do
    member do
      get :rater, :rated
    end
  end
  resources :picposts
  resources :picture_ratings
  resources :picture_comments
  resources :comment_ratings, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]

  root to: 'static_pages#home'

  match '/comment', to: 'picposts#view_comments'
  match '/user_picpost', to: 'users#show_picposts'
  match '/user_comment', to: 'users#show_comments'
  match '/user_feedback', to: 'users#show_feedback'
  match '/user_favorite', to: 'users#show_favorites'

  match '/signup', to: 'users#new'

  match '/welcome', to: 'static_pages#splash'
  match '/about', to: 'static_pages#about'
  match '/help', to: 'static_pages#help'
  match '/contact', to: 'static_pages#contact'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :name, :password, :password_confirmation, :remember_me, :provider, :uid, :good_comment_ratings_count, :bad_comment_ratings_count, :good_picture_ratings_count, :bad_picture_ratings_count #TODO: ensure hacker can't update last 4 on post
  ##attr_accessible :email, :name, :password, :password_confirmation #Removed for devise
  ##has_secure_password # Removed for devise
  has_many :picposts, dependent: :destroy
  has_many :picture_ratings, dependent: :destroy
  has_many :picture_comments, dependent: :destroy

  has_many :comment_ratings, foreign_key: "rater_id", dependent: :destroy
  has_many :rated_users, through: :comment_ratings, source: :rated
  has_many :reverse_comment_ratings, foreign_key: "rated_id",
                                     class_name: "CommentRating",
                                     dependent: :destroy
  has_many :rater_users, through: :reverse_comment_ratings, source: :rater

  has_many :favorites, dependent: :destroy
  has_many :favorite_picposts, through: :favorites, source: :picpost

  ## before_save { |user| user.email = email.downcase } # Removed for devise
  ## before_save :create_remember_token # Removed for devise

  validates :name, presence: true, length: { maximum: 50 }

   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
   validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
   validates :password, presence: true, length: { minimum: 6 }
   validates :password_confirmation, presence: true

#  validates_uniqueness_of :picture_rating, scope: :picpost

  def rating(picpost)
    picture_rating = PictureRating.find_by_user_id_and_picpost_id(self.id, picpost.id)
    return picture_rating.nil? ? nil : picture_rating.rating
  end

  def rate!(picpost, rating)
    picture_ratings.create!(picpost_id: picpost.id, rating: rating)    
  end
 
  def unrate!(picpost)
    picture_ratings.find_by_picpost_id(picpost.id).destroy
  end

  def comment!(picpost, comment)
    picture_comments.create!(picpost_id: picpost.id, comment: comment)
  end

  def rate_comment!(picture_comment,rating)
    comment_ratings.create!(rated_id: picture_comment.user.id, picture_comment_id: picture_comment.id, rating: rating)
  end

  def unrate_comment!(picture_comment)
    comment_ratings.find_by_rated_id_and_picture_comment_id(picture_comment.user.id,picture_comment.id).destroy
  end

  def get_comment_rating(picture_comment)
    comment_ratings.find_by_picture_comment_id(picture_comment.id)
  end
 
  def favored_picpost?(picpost)
    favorites.find_by_picpost_id(picpost.id)
  end

  def favor_picpost!(picpost)
    favorites.create!(picpost_id: picpost.id)
  end

  def unfavor_picpost!(picpost)
    favorites.find_by_picpost_id(picpost.id).destroy
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first

    unless user
      password = Devise.friendly_token[0,20]
      email = "#{auth.uid}@twitter.com"
      user = User.create(name:auth.extra.raw_info.name,
                           provider:auth.provider,
                           uid:auth.uid,
                           email: email,
                           password:password,
                           password_confirmation:password
                           )
    end
    user
  end


  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    
    unless user
      password = Devise.friendly_token[0,20]
      user = User.create(name:auth.extra.raw_info.name,
                           provider:auth.provider,
                           uid:auth.uid,
                           email:auth.info.email,
                           password:password,
                           password_confirmation:password
                           )
    end
    user
  end

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
      data = access_token.info
      user = User.where(:email => data["email"]).first
      password = Devise.friendly_token[0,20]
      unless user
          user = User.create(name: data["name"],
    	    		   email: data["email"],
  	    		   password: password,
                           password_confirmation:password
  	    		  )
      end
      user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  private

    #def create_remember_token
    #  self.remember_token = SecureRandom.urlsafe_base64
    #end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
   @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

   if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter 
    # You need to implement the method below in your model (e.g. app/models/user.rb)
   @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)
   
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require 'net/http'
  #before_filter :signed_in_user, only: [:index, :edit, :update]
  #before_filter :correct_user, only: [:edit, :update]
  #before_filter :admin_user, only: :destroy
  before_filter :authenticate_user!, only: [:index, :edit, :update]

  def index
    #@users = User.paginate(page: params[:page])
    @top_posters = User.order("picposts_count desc").limit(5).all
    @top_commenters = User.order("picture_comments_count desc").limit(5).all
    @most_dashing = User.order("good_picture_ratings_count desc").limit(5).all
    @most_thanked = User.order("good_comment_ratings_count desc").limit(5).all
    @most_favorited = User.order("favorited_count desc").limit(5).all
  end

  def show
    @user = User.find(params[:id])
    @frame = params[:frame]
    if @frame == 'picposts'
      @picposts = @user.picposts
    elsif @frame == 'comments'
      @picposts = @user.picture_comments.map{ |p| p.picpost }.uniq   
    elsif @frame == 'feedback'
      @picposts = @user.picture_ratings.map{ |p| p.picpost }
    elsif @frame == 'favorites'
      @picposts = @user.favorites.map{ |f| f.picpost } 
    else
      @picposts = []
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if verify_recaptcha(@user) && @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  def show_picposts
    @user = User.find(params[:id])
    @picposts = @user.picposts
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show_comments
    @user = User.find(params[:id])
    @picposts = @user.picture_comments.map{ |p| p.picpost }.uniq
    respond_to do |format|
      format.html
      format.js
    end
  end
 
  def show_feedback
    @user = User.find(params[:id])
    @picposts = @user.picture_ratings.map{ |p| p.picpost }
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show_favorites
    @user = User.find(params[:id])
    @picposts = @user.favorites.map{ |f| f.picpost }
    respond_to do |format|
      format.html
      format.js
    end
  end

  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end

end

app/helpers/users_helper.rb
module UsersHelper
 
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/users/_top_commenters.html.erb
<ol style="margin-top: 10px;">
<% users.each do |user| %>
  <li><%= link_to "#{user.name} ( #{user.picture_comments_count} )", user_path(user) %></li>
<% end %>
</ol>

app/views/users/_top_favorited.html.erb
<ol style="margin-top: 10px;">
<% users.each do |user| %>
  <li><%= link_to "#{user.name} ( #{user.favorited_count} )", user_path(user) %></li>
<% end %>
</ol>

app/views/users/_top_posters.html.erb
<ol style="margin-top: 10px;">
<% users.each do |user| %>
  <li><%= link_to "#{user.name} ( #{user.picposts_count} )", user_path(user) %></li>
<% end %>
</ol>

app/views/users/_top_rated.html.erb
<ol style="margin-top: 10px;">
<% users.each do |user| %>
  <li><%= link_to "#{user.name} ( #{user.good_picture_ratings_count} )", user_path(user) %></li>
<% end %>
</ol>

app/views/users/_top_thanked.html.erb
<ol style="margin-top: 10px;">
<% users.each do |user| %>
  <li><%= link_to "#{user.name} ( #{user.good_comment_ratings_count} )", user_path(user) %></li>
<% end %>
</ol>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <%# if current_user.admin? && !current_user?(user) %>
  <!---  | <%#= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %> -->
  <%# end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>
<div style="text-align: center;">
  <h3>Top Fashionistas</h3>
</div>
  
<div>
  <%= render 'users/top_users' %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <br/>
      <%= recaptcha_tags :display => {:theme => 'white'} %>
      <br/>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name ) %>
<div>
  <div style="float: left;">
    <aside style="width: 100px;">
      <section>
        <h1>
          <%= gravatar_for @user %>
          <%= @user.name %>
        </h1>
      </section>
    </aside>

    <ul class="sidebar coolshadow round">

      <%= link_to user_picpost_path(id: @user.id), {remote: true} do %>
        <li id="user_picposts" class="<%= @frame == 'picposts' ? 'bar_selected' : '' %>">Posts<i class="icon-chevron-right"></i></li>
      <% end %>

      <%= link_to user_comment_path(id: @user.id), {remote: true} do %>
        <li id="user_comments" class="<%= @frame == 'comments' ? 'bar_selected' : '' %>">Comments<i class="icon-chevron-right"></i></li>
      <% end %>

      <%= link_to user_feedback_path(id: @user.id), {remote: true} do %>
        <li id="user_feedback" class="<%= @frame == 'feedback' ? 'bar_selected' : '' %>">Feedback<i class="icon-chevron-right"></i></li>
      <% end %>

      <%= link_to user_favorite_path(id: @user.id), {remote: true } do %>
        <li id="user_favorites" class="<%= @frame == 'favorites' ? 'bar_selected' : '' %>">Favorites<i class="icon-chevron-right"></i></li>
      <% end %>
    </ul>

    <div id="stat_container" style="margin-top: 180px;">
      <%= render 'shared/stats_container', picposts: @picposts %>
    </div>

  </div>

  <div class="user_header" style="float: left; width: 800px; padding-left: 30px;">
    <h4>Posts</h4>
    <br/>
  </div>

  <div style="float: left; width: 800px; padding-left: 30px;">
    <div id="user_content_container">
      <%= render 'shared/picposts', picposts: @picposts %> 
    </div>
  </div>
</div>

<div class="clearfix"></div>

app/views/users/show_comments.js.erb
$("#user_content_container").html("<%= escape_javascript render(partial: 'shared/picposts', picposts: @picposts) %>");
setup_masonry(3);
style_sidebar($("li#user_comments"));
setup_favorites_button();
$("div.user_header").html("<h4>Comments</h4><br/>");
$("#stat_container").html("<%= escape_javascript render(partial: 'shared/comment_stats', picposts: @picposts) %>");

app/views/users/show_favorites.js.erb
$("#user_content_container").html("<%= escape_javascript render(partial: 'shared/picposts', picposts: @picposts) %>");
setup_masonry(3);
style_sidebar($("li#user_favorites"));
setup_favorites_button();
$("button.remove_favorite").click(function() {
  $(this).prev('input[name=favorite[reload]]').val("true");
});
$("div.user_header").html("<h4>Favorites</h4><br/>");
$("#stat_container").html("<%= escape_javascript render(partial: 'shared/favorite_stats', picposts: @picposts) %>");

app/views/users/show_feedback.js.erb
$("#user_content_container").html("<%= escape_javascript render(partial: 'shared/picposts', picposts: @picposts) %>");
setup_masonry(3);
style_sidebar($("li#user_feedback"));
setup_favorites_button();
$("div.user_header").html("<h4>Feedback</h4><br/>");
$("#stat_container").html("<%= escape_javascript render(partial: 'shared/feedback_stats', picposts: @picposts) %>");

app/views/users/show_picposts.js.erb
$("#user_content_container").html("<%= escape_javascript render(partial: 'shared/picposts', picposts: @picposts) %>");
setup_masonry(3);
style_sidebar($("li#user_picposts"));
setup_favorites_button();
$("div.user_header").html("<h4>Posts</h4><br/>");
$("#stat_container").html("<%= escape_javascript render(partial: 'shared/picpost_stats', picposts: @picposts) %>");