config/routes.rb
Matcher::Application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }  

  resources :users do
    member do
      get :rater, :rated
    end
  end
  resources :picposts
  resources :picture_ratings
  resources :picture_comments
  resources :comment_ratings, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]

  root to: 'static_pages#home'

  match '/comment', to: 'picposts#view_comments'
  match '/user_picpost', to: 'users#show_picposts'
  match '/user_comment', to: 'users#show_comments'
  match '/user_feedback', to: 'users#show_feedback'
  match '/user_favorite', to: 'users#show_favorites'

  match '/signup', to: 'users#new'

  match '/welcome', to: 'static_pages#splash'
  match '/about', to: 'static_pages#about'
  match '/help', to: 'static_pages#help'
  match '/contact', to: 'static_pages#contact'

end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      a savvy design
    </small>
    <nav>
      <ul>
        <li><%= link_to "About",   about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><a href="http://news.railstutorial.org/">News</a></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_header.html.erb
<header class="navbar" style="position: fixed; top: 0; right: 0; left: 0; z-index: 1030; margin-bottom: 0;">
  <div class="dark_gradient" style="height: 50px;">
    <div class="" style="width: 940px; margin-left: auto; margin-right: auto; overflow: visible;">
      <%= link_to image_tag("logo4.png", alt: "GetupSavvy"), root_path, id: "logo" %>
      <nav>
        <ul class="savnav" style="float: right;">
          <li>
            <%= link_to new_picpost_path, remote: true  do %>
              Add New
            <% end %>
          </li>
          <li><%= link_to "The Runway", root_path %></li>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if user_signed_in? %>
            <li><%#= link_to "Users", users_path %></li>
            <li id="" class="dropdown" style="position: relative;">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <span><%= current_user.name %><b class="caret" style="margin-top: 8px 0px 0px 2px; border-top-color: white; border-bottom-color: white;"></b></span>
              </a>
              <ul class="savdropdown-menu">
                <li><%= link_to "Posts", user_path(current_user, frame: 'picposts') %></li>
                <li><%= link_to "Comments", user_path(current_user, frame: 'comments') %></li>
                <li><%= link_to "Feedback", user_path(current_user, frame: 'feedback') %></li>
                <li><%= link_to "Favorites", user_path(current_user, frame: 'favorites') %></li>
                <li><%= link_to "Settings", edit_user_registration_path %></li>
                <li>
                  <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_social.html.erb
<div class="social_widget coolshadow_big">
  Share
  <br/>
  <br/>
  <div class="fb-like" data-href="http://www.getupsavvy.com" data-send="false" data-layout="button_count" data-width="450" data-show-faces="true"></div>
  <br/><br/>
  <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.getupsavvy.com" data-via="golfclubjunkie">Tweet</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag params[:controller] %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=526942967315807";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

    <%= render 'layouts/header' %>

    <%#= render 'layouts/social' %>

    <div class="container content_wrapper" style="margin-top: 15px;">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>